version: '3.8'
services:
  # ... Veritabanları (Değişiklik yok)
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  checkoutdb:
    image: redis
  discountdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root # MSSQL için user tanımı gerekli
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
  stockdb:
    image: mysql:8.0
    user: root
    
  # Mikroservisler ve Gateway (Build tanımları)
  catalogapi:
    image: multishop/catalogapi:latest # Daha iyi bir imaj ismi
    build: 
      context: .
      dockerfile: Services/Catalog/MultiShop.Catalog/Dockerfile
  elasticsyncworker:
    image: multishop/elasticsyncworker:latest # Daha iyi bir imaj ismi
    build: 
      context: .
      dockerfile: Services/Catalog/Catalog.ElasticSyncWorker/Dockerfile
  outboxworker:
    image: multishop/outboxworker:latest 
    build: 
      context: .
      dockerfile: Services/Catalog/OutboxWorker/MultiShop.Catalog.OutboxWorker/Dockerfile
  identityserverapi:
    image: multishop/identityserverapi:latest
    build: 
      context: .
      dockerfile: IdentityServer/MultiShop.IdentityServer/Dockerfile
  orderapi:
    image: multishop/orderapi:latest
    build: 
      context: .
      dockerfile: Services/Order/Presentation/MultiShop.Order.WebApi/Dockerfile
  stockapi:
    image: multishop/stockapi:latest
    build: 
      context: .
      dockerfile: Services/Stock/Presentation/MultiShop.Stock.WebApi/Dockerfile
  paymentapi:
    image: multishop/paymentapi:latest
    build: 
      context: .
      dockerfile: Services/Payment/MultiShop.Payment/Dockerfile
  checkoutapi:
    image: multishop/checkoutapi:latest
    build: 
      context: .
      dockerfile: Services/Checkout/MultiShop.Checkout/Dockerfile
  notificationapi:
    image: multishop/notificationapi:latest
    build: 
      context: .
      dockerfile: Services/Notification/MultiShop.Notification/Dockerfile
  gatewayapi:
    image: multishop/gatewayapi:latest
    build: 
      context: .
      dockerfile: ApiGateway/MultiShop.OcelotGateway/Dockerfile
  monitorapi:
    image: multishop/monitorapi:latest
    build: 
      context: .
      dockerfile: Services/Monitor/MultiShop.Monitor/Dockerfile # Yeni Monitor projenizin yolu
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
  rabbitmq:
    image: rabbitmq:3-management
   


    
       
# Volumes (Değişiklik yok)
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:
  stockdb_volume:

  esdata:
# Network tanımını kaldırın veya basitleştirin
networks:
  default:
    driver: overlay # Swarm için default olarak overlay kullanılması tavsiye edilir.
    # Harici ağ tanımını kaldırdık