version: '3.8'
services:
  # ... Veritabanları (Değişiklik yok)
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root # MSSQL için user tanımı gerekli
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    
  # Mikroservisler ve Gateway (Build tanımları)
  catalogapi:
    image: multishop/catalogapi:latest # Daha iyi bir imaj ismi
    build: 
      context: .
      dockerfile: Services/Catalog/MultiShop.Catalog/Dockerfile
  elasticsyncworker:
    image: multishop/elasticsyncworker:latest # Daha iyi bir imaj ismi
    build: 
      context: .
      dockerfile: Services/Catalog/Catalog.ElasticSyncWorker/Dockerfile
  identityserverapi:
    image: multishop/identityserverapi:latest
    build: 
      context: .
      dockerfile: IdentityServer/MultiShop.IdentityServer/Dockerfile
  gatewayapi:
    image: multishop/gatewayapi:latest
    build: 
      context: .
      dockerfile: ApiGateway/MultiShop.OcelotGateway/Dockerfile
  monitorapi:
    image: multishop/monitorapi:latest
    build: 
      context: .
      dockerfile: Services/Monitor/MultiShop.Monitor/Dockerfile # Yeni Monitor projenizin yolu
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
  rabbitmq:
    image: rabbitmq:3-management
   


    
       
# Volumes (Değişiklik yok)
volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:
  esdata:
# Network tanımını kaldırın veya basitleştirin
networks:
  default:
    driver: overlay # Swarm için default olarak overlay kullanılması tavsiye edilir.
    # Harici ağ tanımını kaldırdık