version: '3.8'
services:
    # --- Veritabanı Servisleri (Tekil) ---
    catalogdb:
      container_name: catalogdb
      restart: always
      ports:
        - "27017:27017"
      command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
      volumes:
        - catalogdb_volume:/data/db
      # Veritabanları ölçeklenmediği için deploy ayarı Swarm'da gereklidir
      deploy:
        mode: replicated
        replicas: 1 # Tek bir veritabanı örneği
        placement:
          constraints: [node.role == manager] # Genellikle manager node'da tutulur

    # Diğer DB'ler (basketdb, discountdb, identitydb, orderdb) benzer şekilde deploy: replicas: 1 alır.
    identitydb:
      container_name: identitydb
      restart: always
      ports:
        - "1433:1433" # 1433 portunu dışarı açıyoruz
      volumes:
        - identitydb_volume:/var/opt/mssql
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=123456aA*
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.role == manager]
    rabbitmq:
      container_name: rabbitmq
      restart: always
      image: rabbitmq:3-management
      ports:
       - "5672:5672"
       - "15672:15672"
    # --- Yük Dengelemeli Servisler ---
    
    # 1. Katalog API (2 Replica)
    catalogapi:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - IdentityServerUrl=http://identityserverapi:80 # IdentityServer'ın servis adını kullanıyoruz
        - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017/?replicaSet=rs0 # DB servis adını kullanıyoruz
      ports:
        - "7070:80" # Bu port sadece ilk replica için açılır, Swarm load balancing'i bu port üzerinden yapar.
      depends_on:
        - catalogdb
        - rabbitmq
        - identityserverapi
      deploy:
        mode: replicated
        replicas: 1 # Yük dengeleme için 2 kopya
        restart_policy:
          condition: any
    elasticsyncworker:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      depends_on:
        - rabbitmq
        - elasticsearch
      deploy:
        mode: replicated
        replicas: 2 # Yük dengeleme için 2 kopya
        restart_policy:
          condition: any
    # 2. IdentityServer API (1 Replica)
    identityserverapi:
      restart: on-failure
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__DefaultConnection=Server=identitydb,1433;Database=IdentityDb;User=sa;Password=123456aA*;Encrypt=False;TrustServerCertificate=True;
        - IdentityServer:IssuerUri=http://localhost:5001
        - IdentityServer__IssuerUri=http://localhost:5001
      ports:
        - "5001:80"
      volumes:
        - ./data-protection-keys:/root/.aspnet/DataProtection-Keys
      depends_on:
        - identitydb
      deploy:
        mode: replicated
        replicas: 1 # Identity Server genellikle tek kopya çalışır
        restart_policy:
          condition: on-failure
          
    # 3. Gateway API (3 Replica)
    gatewayapi:
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
        - IdentityServerUrl=http://identityserverapi:80
      ports:
        - "5000:80" # Dışarıdan erişim için 5000:80 portunu açıyoruz
      depends_on:
        - identityserverapi
      deploy:
        mode: replicated
        replicas: 3 # Yük dengeleme için 3 kopya
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.role == manager] # Gateway'i manager node'da tutmak iyi bir uygulamadır.

    monitorapi:
      restart: always
      environment:
        - ASPNETCORE_URLS=http://+:80
      # Health Check UI'ı bir In-Memory DB kullanmak yerine gerçek bir DB'de tutmak HA için iyidir.
      ports:
        - "7079:80" # UI'a 5002 portundan erişeceğiz
      depends_on:
        - catalogapi # UI'ın monitör edeceği servisler
        - gatewayapi
        - identityserverapi
     
      deploy:
        mode: replicated
        replicas: 1 # UI genellikle tek kopya çalışır      
    elasticsearch:
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
        - xpack.security.enabled=false
        - xpack.security.http.ssl.enabled=false
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - esdata:/usr/share/elasticsearch/data
      deploy:
        mode: replicated
        replicas: 1
     

    kibana:
      container_name: kibana
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch
      deploy:
        mode: replicated
        replicas: 1